# Generated by Django 3.2.8 on 2021-11-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='image',
            field=models.ImageField(upload_to='images/contributor/'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='logo',
            field=models.ImageField(upload_to='images/logo/'),
        ),
    ]
